services:
  # Redis service (to only be used in dev
  redis:
    image: redis:7.4
    container_name: redis_db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Only run Redis locally; skip in prod
    deploy:
      replicas: ${REDIS_REPLICAS:-1}

  api:
    build: .
    container_name: energyapi
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      # default to dev if not set
      - APP_ENV=${APP_ENV:-dev}
    restart: unless-stopped

volumes:
  redis_data:
