services:
  api:
    build: .
    container_name: energyapi
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # default to dev if not set
      - APP_ENV=${APP_ENV:-dev}
    restart: unless-stopped

